image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: open-preview
    visibility: public
tasks:
  - init: >
      (cp .env.example .env || true) &&
      pipenv install &&
  bash database.sh &&
      python docs/assets/greeting.py back
  - command: >
      npm install &&
      python docs/assets/greeting.py front
    openMode: split-right

vscode:
  extensions:
    - esbenp.prettier-vscode
